version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - 5440:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6381:6379
    volumes:
      - redis-data:/data
  rails:
    build: .
    image: ma-rails
    command: sh -c 'cd /app/ma && bundle install && rails s -b 0.0.0.0'
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    env_file:
      - .env
  sidekiq:
    image: ma-rails
    command: sh -c 'cd /app/ma && sidekiq'
    depends_on:
      - redis
      - rails
    env_file:
      - .env

volumes:
  pg-data:
    driver: local
  redis-data:
    driver: local